language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test-headless
    - stage: deploy
      before_script:
        - npm install -g @angular/cli
      script: ng build --prod --base-href https://bamanczak.github.io/pesel/
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/pesel
        on:
          branch: master
stages:
  - lint
  - test
  - deploy
